### ISSUE TITLE
Creating a recurring event with number of repetitions set to 0 causes huge performance issue

### ISSUE THREAD

**Issue by eilst** [savoirfairelinux/project-addons#308]
https://github.com/odoo/odoo/issues/30020
steps to reproduce:
Create a new calendar event that is recurrent, repeated every 1 week with number of repetitions = 0, to be repeated on Mon, Tue, Wed, Thu:

Current behavior:
This creates thousands of virtual events, causing a huge performance issue - most likely causing a CPU timeout.

Expected behavior:
There are two options here:

(quick fix) require to set a number of repetitions > 0
If a user sets 0 as number of repetitions, assume that it's going to happen until a defined period (e.g. 1 year from today's date by default), and then set a cron job that recreates this same event every year.
Seems that Google calendar does something similar to 2). If you create a recurring event with infinite occurrences, you'll see the calendar events for 1 year. After that you won't see them. At least immediately. Perhaps they will eventually appear as you come closer to the next year¿?

**Comment by jananjoy** [comment]
Closed the bug and created a task for this issue. ( Look more  on performance issue)
