### ISSUE TITLE
Create Activity without Event or predefined event

### ISSUE THREAD

**Issue by eilst** [savoirfairelinux/project-addons#320]
**Describe the bug**
An error is produced when we try to create an activity without an event or if we put a predefined event as the event of the new activity.  

**To Reproduce**
1. Go to Create a new activity with predefined odoo event
2. Click on save
3. See error

**Expected behavior**
Either the activity should be created or the selection of event on the new activity should be required without predefined events.

**Comment by jananjoy** [comment]
@eilst  Seems it is working at the current build. Still investigating

**Comment by jananjoy** [comment]
Working fine at the 11.0 latest build. Tested both the conditions.
