### ISSUE TITLE
Create activity before event

### ISSUE THREAD

**Issue by lgharib** [savoirfairelinux/project-addons#321]
**Describe the bug**
When creating an Activity without assigning an Event and then creating an Event and affecting it to an activity crashes the system

**To Reproduce**
1. Create an Activity without affecting an Event
2. Create an Event
3. Go back to the Activity and click edit and affect the previously create Event to the Activity
4. Click save

**Expected behavior**
The activity is saved with the affected Event

**Screenshots**
![image](https://user-images.githubusercontent.com/43585585/51417214-f85ec100-1b4a-11e9-9736-7d9d5d4519b3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version Quantum

**Comment by jananjoy** [comment]
@ : Testing this Bug to reproduce

**Comment by jananjoy** [comment]
Working fine at the current 11.0  latest build
